name: Ansible lint
on: [push, pull_request]
jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: ansible-lint
      uses: ansible/ansible-lint-action@master
      with:
        targets: ""